"""Visualization utilities for displaying GAICo-generated plots."""

from pathlib import Path
from typing import Optional
import streamlit as st

from config import LLM_FAQ_PLOTS_DIR, CASE_STUDY_DIR


def display_plot(image_path: str, caption: Optional[str] = None) -> None:
    """Display a plot image if it exists, otherwise show error."""
    if Path(image_path).exists():
        st.image(image_path, caption=caption)
    else:
        st.error(f"❌ Image not found: {image_path}")


def display_case_study_plots(plot_type: str = "radar") -> None:
    """Display case study radar or bar plots (modality quality and plan coherence)."""
    if plot_type not in ["radar", "bars"]:
        st.error("Plot type must be 'radar' or 'bars'")
        return
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("### Modality Generation Quality")
        st.caption("Evaluates image and audio quality generated by specialist models")
        display_plot(str(CASE_STUDY_DIR / "figures" / f"modality_quality_{plot_type}.png"))
    
    with col2:
        st.markdown("### Plan Coherence")
        st.caption("Evaluates text planning and structured data accuracy")
        display_plot(str(CASE_STUDY_DIR / "figures" / f"plan_coherence_{plot_type}.png"))


def display_llm_faq_plots(plot_type: str = "radar", metric: Optional[str] = None) -> None:
    """Display LLM FAQ comparison plots (radar, bar, heatmaps, or line)."""
    valid_types = ["radar", "bar", "heatmaps", "line"]
    if plot_type not in valid_types:
        st.error(f"Plot type must be one of: {', '.join(valid_types)}")
        return
    
    plot_dir = LLM_FAQ_PLOTS_DIR / plot_type
    
    if not plot_dir.exists():
        st.warning(f"No plots found in {plot_dir}")
        return
    
    available_plots = sorted(plot_dir.glob("*.png"))
    
    if not available_plots:
        st.warning(f"No PNG files found in {plot_dir}")
        return
    
    # Handle specific metric request
    if metric:
        suffix = "_radar_chart" if plot_type == "radar" else f"_{plot_type}"
        metric_plot = plot_dir / f"{metric}{suffix}.png"
        if metric_plot.exists():
            display_plot(str(metric_plot), caption=f"{metric} - {plot_type.title()}")
        else:
            st.error(f"Plot not found: {metric_plot.name}")
        return
    
    # Display all plots based on type
    if plot_type == "radar":
        overall = plot_dir / "overall_radar_chart.png"
        if overall.exists():
            display_plot(str(overall), caption="Overall Multi-Metric Comparison")
            st.divider()
        
        st.markdown("#### Individual Metric Radars")
        cols = st.columns(3)
        for idx, p in enumerate([x for x in available_plots if "overall" not in x.name]):
            with cols[idx % 3]:
                display_plot(str(p), caption=p.stem.replace("_radar_chart", ""))
    
    elif plot_type == "bar":
        for p in available_plots:
            display_plot(str(p), caption=p.stem.replace("_", " ").title())
    
    else:  # heatmaps or line
        cols = st.columns(2)
        suffix = "_heatmap" if plot_type == "heatmaps" else "_line_plot"
        for idx, p in enumerate(available_plots):
            with cols[idx % 2]:
                display_plot(str(p), caption=p.stem.replace(suffix, ""))
