"""LLM FAQ page - Multi-model comparison with various visualizations."""

import streamlit as st
import pandas as pd
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from config import DATA_DIR, LLM_FAQ_PLOTS_DIR
from utils.ui_components import display_footer
from utils.visualizations import display_llm_faq_plots

st.header("💬 E1: LLM FAQ Evaluation")

st.markdown("""
Comprehensive comparison of multiple LLMs on a FAQ dataset using multiple metrics.
GAICo evaluates text similarity and generates visualizations for detailed analysis.
""")

tab1, tab2 = st.tabs(["📊 Example Comparison", "📈 Visualizations"])

# ============================================================================
# TAB 1: Example Comparison
# ============================================================================
with tab1:
    st.subheader("📥 Input Data - LLM Response Comparison")
    
    # Load the data
    csv_path = DATA_DIR / "llm_responses_processed.csv"
    
    if csv_path.exists():
        df = pd.read_csv(csv_path)
        
        # Get questions for selection
        questions = df['question'].tolist()
        selected_q_idx = st.selectbox(
            "Select Question",
            range(len(questions)),
            format_func=lambda x: questions[x][:80] + "..." if len(questions[x]) > 80 else questions[x]
        )
        
        selected_row = df.iloc[selected_q_idx]
        
        st.divider()
        
        st.markdown(f"**Question:** {selected_row['question']}")
        
        st.divider()
        
        # Display responses side by side
        col1, col2 = st.columns(2)
        
        def format_text(text):
            """Format text for display."""
            if pd.isna(text):
                return "No response"
            text = str(text)
            text = text.replace('\\n', '\n')
            text = text.replace('\\t', '\t')
            return text
        
        with col1:
            st.markdown("**DeepSeek R1 Response**")
            r1_text = format_text(selected_row.get('r1', ''))
            st.markdown(
                f'<div style="background-color: #e8f4f8; padding: 1rem; border-radius: 0.5rem; max-height: 400px; overflow-y: auto; white-space: pre-wrap; font-size: 0.85rem;">{r1_text}</div>',
                unsafe_allow_html=True
            )
        
        with col2:
            st.markdown("**Llama 3.3 Response**")
            llama_text = format_text(selected_row.get('llama3.3', ''))
            st.markdown(
                f'<div style="background-color: #e8f8e8; padding: 1rem; border-radius: 0.5rem; max-height: 400px; overflow-y: auto; white-space: pre-wrap; font-size: 0.85rem;">{llama_text}</div>',
                unsafe_allow_html=True
            )
        
        st.divider()
        
        st.markdown("### 📊 GAICo Evaluation Metrics")
        st.info("GAICo computes metrics like **BLEU**, **ROUGE-L**, **BERTScore**, **Jaccard**, **Levenshtein**, and **JSD** to compare these responses. See the Visualizations tab for aggregate results across all questions.")
        
    else:
        st.error("LLM responses CSV not found")

# ============================================================================
# TAB 2: Visualizations
# ============================================================================
with tab2:
    st.subheader("📈 GAICo-Generated Visualizations")
    
    st.markdown("""
    These visualizations were generated by GAICo to compare model performance across multiple metrics.
    """)
    
    plot_type = st.selectbox(
        "Select Visualization Type",
        options=["radar", "bar", "heatmaps", "line"],
        format_func=lambda x: {
            "radar": "📡 Radar Charts (Multi-Metric Overview)",
            "bar": "📊 Bar Charts (Model Comparison)",
            "heatmaps": "🔥 Heatmaps (Score Matrix)",
            "line": "📈 Line Plots (Trend Analysis)"
        }[x]
    )
    
    st.divider()
    
    display_llm_faq_plots(plot_type=plot_type)

st.divider()

with st.expander("📖 Metric Descriptions"):
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("""
        **BLEU** (Bilingual Evaluation Understudy)
        - N-gram precision based metric
        - Range: 0.0 to 1.0 (higher is better)
        - Best for: Translation, summarization
        
        **ROUGE-L** (Recall-Oriented Understudy)
        - Longest common subsequence based
        - Range: 0.0 to 1.0 (higher is better)
        - Best for: Summarization quality
        
        **BERTScore**
        - Semantic similarity using BERT embeddings
        - Range: 0.0 to 1.0 (higher is better)
        - Best for: Meaning preservation
        """)
    
    with col2:
        st.markdown("""
        **Jaccard Similarity**
        - Token-level set overlap
        - Range: 0.0 to 1.0 (higher is better)
        - Best for: Vocabulary coverage
        
        **Levenshtein Distance**
        - Edit distance normalized
        - Range: 0.0 to 1.0 (higher is better)
        - Best for: String similarity
        
        **JSD** (Jensen-Shannon Divergence)
        - Distribution difference
        - Range: 0.0 to 1.0 (lower is better)
        - Best for: Probability distribution comparison
        """)

display_footer()
